import { PhotoInfo } from "@/types/photoInfo";

export const VERTICAL_PHOTOS: PhotoInfo[] = [
  {
    bigPath: "/photos/big/v0.jpg",
    mediumPath: "/photos/medium/v0.jpg",
    smallPath: "/photos/small/v0.jpg",
    photoId: "v0",
    isVertical: true,
  },
  {
    bigPath: "/photos/big/v1.jpg",
    mediumPath: "/photos/medium/v1.jpg",
    smallPath: "/photos/small/v1.jpg",
    photoId: "v1",
    isVertical: true,
  },
  {
    bigPath: "/photos/big/v2.jpg",
    mediumPath: "/photos/medium/v2.jpg",
    smallPath: "/photos/small/v2.jpg",
    photoId: "v2",
    isVertical: true,
  },
  {
    bigPath: "/photos/big/v3.jpg",
    mediumPath: "/photos/medium/v3.jpg",
    smallPath: "/photos/small/v3.jpg",
    photoId: "v3",
    isVertical: true,
  },
  {
    bigPath: "/photos/big/v4.jpg",
    mediumPath: "/photos/medium/v4.jpg",
    smallPath: "/photos/small/v4.jpg",
    photoId: "v4",
    isVertical: true,
  },
  {
    bigPath: "/photos/big/v5.jpg",
    mediumPath: "/photos/medium/v5.jpg",
    smallPath: "/photos/small/v5.jpg",
    photoId: "v5",
    isVertical: true,
  },
  {
    bigPath: "/photos/big/v6.jpg",
    mediumPath: "/photos/medium/v6.jpg",
    smallPath: "/photos/small/v6.jpg",
    photoId: "v6",
    isVertical: true,
  },
  {
    bigPath: "/photos/big/v7.jpg",
    mediumPath: "/photos/medium/v7.jpg",
    smallPath: "/photos/small/v7.jpg",
    photoId: "v7",
    isVertical: true,
  },
  {
    bigPath: "/photos/big/v8.jpg",
    mediumPath: "/photos/medium/v8.jpg",
    smallPath: "/photos/small/v8.jpg",
    photoId: "v8",
    isVertical: true,
  },
  {
    bigPath: "/photos/big/v9.jpg",
    mediumPath: "/photos/medium/v9.jpg",
    smallPath: "/photos/small/v9.jpg",
    photoId: "v9",
    isVertical: true,
  },
  {
    bigPath: "/photos/big/v10.jpg",
    mediumPath: "/photos/medium/v10.jpg",
    smallPath: "/photos/small/v10.jpg",
    photoId: "v10",
    isVertical: true,
  },
  {
    bigPath: "/photos/big/v11.jpg",
    mediumPath: "/photos/medium/v11.jpg",
    smallPath: "/photos/small/v11.jpg",
    photoId: "v11",
    isVertical: true,
  },
  {
    bigPath: "/photos/big/v12.jpg",
    mediumPath: "/photos/medium/v12.jpg",
    smallPath: "/photos/small/v12.jpg",
    photoId: "v12",
    isVertical: true,
  },
  {
    bigPath: "/photos/big/v13.jpg",
    mediumPath: "/photos/medium/v13.jpg",
    smallPath: "/photos/small/v13.jpg",
    photoId: "v13",
    isVertical: true,
  },
  {
    bigPath: "/photos/big/v14.jpg",
    mediumPath: "/photos/medium/v14.jpg",
    smallPath: "/photos/small/v14.jpg",
    photoId: "v14",
    isVertical: true,
  },
  {
    bigPath: "/photos/big/v15.jpg",
    mediumPath: "/photos/medium/v15.jpg",
    smallPath: "/photos/small/v15.jpg",
    photoId: "v15",
    isVertical: true,
  },
  {
    bigPath: "/photos/big/v16.jpg",
    mediumPath: "/photos/medium/v16.jpg",
    smallPath: "/photos/small/v16.jpg",
    photoId: "v16",
    isVertical: true,
  },
  {
    bigPath: "/photos/big/v17.jpg",
    mediumPath: "/photos/medium/v17.jpg",
    smallPath: "/photos/small/v17.jpg",
    photoId: "v17",
    isVertical: true,
  },
];

export const HORIZONTAL_PHOTOS: PhotoInfo[] = [
  {
    bigPath: "/photos/big/h0.jpg",
    mediumPath: "/photos/medium/h0.jpg",
    smallPath: "/photos/small/h0.jpg",
    photoId: "h0",
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h1.jpg",
    mediumPath: "/photos/medium/h1.jpg",
    smallPath: "/photos/small/h1.jpg",
    photoId: "h1",
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h2.jpg",
    mediumPath: "/photos/medium/h2.jpg",
    smallPath: "/photos/small/h2.jpg",
    photoId: "h2",
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h3.jpg",
    mediumPath: "/photos/medium/h3.jpg",
    smallPath: "/photos/small/h3.jpg",
    photoId: "h3",
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h4.jpg",
    mediumPath: "/photos/medium/h4.jpg",
    smallPath: "/photos/small/h4.jpg",
    photoId: "h4",
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h5.jpg",
    mediumPath: "/photos/medium/h5.jpg",
    smallPath: "/photos/small/h5.jpg",
    photoId: "h5",
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h6.jpg",
    mediumPath: "/photos/medium/h6.jpg",
    smallPath: "/photos/small/h6.jpg",
    photoId: "h6",
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h7.jpg",
    mediumPath: "/photos/medium/h7.jpg",
    smallPath: "/photos/small/h7.jpg",
    photoId: "h7",
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h8.jpg",
    mediumPath: "/photos/medium/h8.jpg",
    smallPath: "/photos/small/h8.jpg",
    photoId: "h8",
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h9.jpg",
    mediumPath: "/photos/medium/h9.jpg",
    smallPath: "/photos/small/h9.jpg",
    photoId: "h9",
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h10.jpg",
    mediumPath: "/photos/medium/h10.jpg",
    smallPath: "/photos/small/h10.jpg",
    photoId: "h10",
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h11.jpg",
    mediumPath: "/photos/medium/h11.jpg",
    smallPath: "/photos/small/h11.jpg",
    photoId: "h11",
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h12.jpg",
    mediumPath: "/photos/medium/h12.jpg",
    smallPath: "/photos/small/h12.jpg",
    photoId: "h12",
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h13.jpg",
    mediumPath: "/photos/medium/h13.jpg",
    smallPath: "/photos/small/h13.jpg",
    photoId: "h13",
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h14.jpg",
    mediumPath: "/photos/medium/h14.jpg",
    smallPath: "/photos/small/h14.jpg",
    photoId: "h14",
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h15.jpg",
    mediumPath: "/photos/medium/h15.jpg",
    smallPath: "/photos/small/h15.jpg",
    photoId: "h15",
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h16.jpg",
    mediumPath: "/photos/medium/h16.jpg",
    smallPath: "/photos/small/h16.jpg",
    photoId: "h16",
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h17.jpg",
    mediumPath: "/photos/medium/h17.jpg",
    smallPath: "/photos/small/h17.jpg",
    photoId: "h17",
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h18.jpg",
    mediumPath: "/photos/medium/h18.jpg",
    smallPath: "/photos/small/h18.jpg",
    photoId: "h18",
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h19.jpg",
    mediumPath: "/photos/medium/h19.jpg",
    smallPath: "/photos/small/h19.jpg",
    photoId: "h19",
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h20.jpg",
    mediumPath: "/photos/medium/h20.jpg",
    smallPath: "/photos/small/h20.jpg",
    photoId: "h20",
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h21.jpg",
    mediumPath: "/photos/medium/h21.jpg",
    smallPath: "/photos/small/h21.jpg",
    photoId: "h21",
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h22.jpg",
    mediumPath: "/photos/medium/h22.jpg",
    smallPath: "/photos/small/h22.jpg",
    photoId: "h22",
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h23.jpg",
    mediumPath: "/photos/medium/h23.jpg",
    smallPath: "/photos/small/h23.jpg",
    photoId: "h23",
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h24.jpg",
    mediumPath: "/photos/medium/h24.jpg",
    smallPath: "/photos/small/h24.jpg",
    photoId: "h24",
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h25.jpg",
    mediumPath: "/photos/medium/h25.jpg",
    smallPath: "/photos/small/h25.jpg",
    photoId: "h25",
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h26.jpg",
    mediumPath: "/photos/medium/h26.jpg",
    smallPath: "/photos/small/h26.jpg",
    photoId: "h26",
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h27.jpg",
    mediumPath: "/photos/medium/h27.jpg",
    smallPath: "/photos/small/h27.jpg",
    photoId: "h27",
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h28.jpg",
    mediumPath: "/photos/medium/h28.jpg",
    smallPath: "/photos/small/h28.jpg",
    photoId: "h28",
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h29.jpg",
    mediumPath: "/photos/medium/h29.jpg",
    smallPath: "/photos/small/h29.jpg",
    photoId: "h29",
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h30.jpg",
    mediumPath: "/photos/medium/h30.jpg",
    smallPath: "/photos/small/h30.jpg",
    photoId: "h30",
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h31.jpg",
    mediumPath: "/photos/medium/h31.jpg",
    smallPath: "/photos/small/h31.jpg",
    photoId: "h31",
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h32.jpg",
    mediumPath: "/photos/medium/h32.jpg",
    smallPath: "/photos/small/h32.jpg",
    photoId: "h32",
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h33.jpg",
    mediumPath: "/photos/medium/h33.jpg",
    smallPath: "/photos/small/h33.jpg",
    photoId: "h33",
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h34.jpg",
    mediumPath: "/photos/medium/h34.jpg",
    smallPath: "/photos/small/h34.jpg",
    photoId: "h34",
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h35.jpg",
    mediumPath: "/photos/medium/h35.jpg",
    smallPath: "/photos/small/h35.jpg",
    photoId: "h35",
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h36.jpg",
    mediumPath: "/photos/medium/h36.jpg",
    smallPath: "/photos/small/h36.jpg",
    photoId: "h36",
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h37.jpg",
    mediumPath: "/photos/medium/h37.jpg",
    smallPath: "/photos/small/h37.jpg",
    photoId: "h37",
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h38.jpg",
    mediumPath: "/photos/medium/h38.jpg",
    smallPath: "/photos/small/h38.jpg",
    photoId: "h38",
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h39.jpg",
    mediumPath: "/photos/medium/h39.jpg",
    smallPath: "/photos/small/h39.jpg",
    photoId: "h39",
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h40.jpg",
    mediumPath: "/photos/medium/h40.jpg",
    smallPath: "/photos/small/h40.jpg",
    photoId: "h40",
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h41.jpg",
    mediumPath: "/photos/medium/h41.jpg",
    smallPath: "/photos/small/h41.jpg",
    photoId: "h41",
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h42.jpg",
    mediumPath: "/photos/medium/h42.jpg",
    smallPath: "/photos/small/h42.jpg",
    photoId: "h42",
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h43.jpg",
    mediumPath: "/photos/medium/h43.jpg",
    smallPath: "/photos/small/h43.jpg",
    photoId: "h43",
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h44.jpg",
    mediumPath: "/photos/medium/h44.jpg",
    smallPath: "/photos/small/h44.jpg",
    photoId: "h44",
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h45.jpg",
    mediumPath: "/photos/medium/h45.jpg",
    smallPath: "/photos/small/h45.jpg",
    photoId: "h45",
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h46.jpg",
    mediumPath: "/photos/medium/h46.jpg",
    smallPath: "/photos/small/h46.jpg",
    photoId: "h46",
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h47.jpg",
    mediumPath: "/photos/medium/h47.jpg",
    smallPath: "/photos/small/h47.jpg",
    photoId: "h47",
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h48.jpg",
    mediumPath: "/photos/medium/h48.jpg",
    smallPath: "/photos/small/h48.jpg",
    photoId: "h48",
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h49.jpg",
    mediumPath: "/photos/medium/h49.jpg",
    smallPath: "/photos/small/h49.jpg",
    photoId: "h49",
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h50.jpg",
    mediumPath: "/photos/medium/h50.jpg",
    smallPath: "/photos/small/h50.jpg",
    photoId: "h50",
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h51.jpg",
    mediumPath: "/photos/medium/h51.jpg",
    smallPath: "/photos/small/h51.jpg",
    photoId: "h51",
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h52.jpg",
    mediumPath: "/photos/medium/h52.jpg",
    smallPath: "/photos/small/h52.jpg",
    photoId: "h52",
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h53.jpg",
    mediumPath: "/photos/medium/h53.jpg",
    smallPath: "/photos/small/h53.jpg",
    photoId: "h53",
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h54.jpg",
    mediumPath: "/photos/medium/h54.jpg",
    smallPath: "/photos/small/h54.jpg",
    photoId: "h54",
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h55.jpg",
    mediumPath: "/photos/medium/h55.jpg",
    smallPath: "/photos/small/h55.jpg",
    photoId: "h55",
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h56.jpg",
    mediumPath: "/photos/medium/h56.jpg",
    smallPath: "/photos/small/h56.jpg",
    photoId: "h56",
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h57.jpg",
    mediumPath: "/photos/medium/h57.jpg",
    smallPath: "/photos/small/h57.jpg",
    photoId: "h57",
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h58.jpg",
    mediumPath: "/photos/medium/h58.jpg",
    smallPath: "/photos/small/h58.jpg",
    photoId: "h58",
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h59.jpg",
    mediumPath: "/photos/medium/h59.jpg",
    smallPath: "/photos/small/h59.jpg",
    photoId: "h59",
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h60.jpg",
    mediumPath: "/photos/medium/h60.jpg",
    smallPath: "/photos/small/h60.jpg",
    photoId: "h60",
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h61.jpg",
    mediumPath: "/photos/medium/h61.jpg",
    smallPath: "/photos/small/h61.jpg",
    photoId: "h61",
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h62.jpg",
    mediumPath: "/photos/medium/h62.jpg",
    smallPath: "/photos/small/h62.jpg",
    photoId: "h62",
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h63.jpg",
    mediumPath: "/photos/medium/h63.jpg",
    smallPath: "/photos/small/h63.jpg",
    photoId: "h63",
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h64.jpg",
    mediumPath: "/photos/medium/h64.jpg",
    smallPath: "/photos/small/h64.jpg",
    photoId: "h64",
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h65.jpg",
    mediumPath: "/photos/medium/h65.jpg",
    smallPath: "/photos/small/h65.jpg",
    photoId: "h65",
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h66.jpg",
    mediumPath: "/photos/medium/h66.jpg",
    smallPath: "/photos/small/h66.jpg",
    photoId: "h66",
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h67.jpg",
    mediumPath: "/photos/medium/h67.jpg",
    smallPath: "/photos/small/h67.jpg",
    photoId: "h67",
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h68.jpg",
    mediumPath: "/photos/medium/h68.jpg",
    smallPath: "/photos/small/h68.jpg",
    photoId: "h68",
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h69.jpg",
    mediumPath: "/photos/medium/h69.jpg",
    smallPath: "/photos/small/h69.jpg",
    photoId: "h69",
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h70.jpg",
    mediumPath: "/photos/medium/h70.jpg",
    smallPath: "/photos/small/h70.jpg",
    photoId: "h70",
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h71.jpg",
    mediumPath: "/photos/medium/h71.jpg",
    smallPath: "/photos/small/h71.jpg",
    photoId: "h71",
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h72.jpg",
    mediumPath: "/photos/medium/h72.jpg",
    smallPath: "/photos/small/h72.jpg",
    photoId: "h72",
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h73.jpg",
    mediumPath: "/photos/medium/h73.jpg",
    smallPath: "/photos/small/h73.jpg",
    photoId: "h73",
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h74.jpg",
    mediumPath: "/photos/medium/h74.jpg",
    smallPath: "/photos/small/h74.jpg",
    photoId: "h74",
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h75.jpg",
    mediumPath: "/photos/medium/h75.jpg",
    smallPath: "/photos/small/h75.jpg",
    photoId: "h75",
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h76.jpg",
    mediumPath: "/photos/medium/h76.jpg",
    smallPath: "/photos/small/h76.jpg",
    photoId: "h76",
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h77.jpg",
    mediumPath: "/photos/medium/h77.jpg",
    smallPath: "/photos/small/h77.jpg",
    photoId: "h77",
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h78.jpg",
    mediumPath: "/photos/medium/h78.jpg",
    smallPath: "/photos/small/h78.jpg",
    photoId: "h78",
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h79.jpg",
    mediumPath: "/photos/medium/h79.jpg",
    smallPath: "/photos/small/h79.jpg",
    photoId: "h79",
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h80.jpg",
    mediumPath: "/photos/medium/h80.jpg",
    smallPath: "/photos/small/h80.jpg",
    photoId: "h80",
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h81.jpg",
    mediumPath: "/photos/medium/h81.jpg",
    smallPath: "/photos/small/h81.jpg",
    photoId: "h81",
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h82.jpg",
    mediumPath: "/photos/medium/h82.jpg",
    smallPath: "/photos/small/h82.jpg",
    photoId: "h82",
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h83.jpg",
    mediumPath: "/photos/medium/h83.jpg",
    smallPath: "/photos/small/h83.jpg",
    photoId: "h83",
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h84.jpg",
    mediumPath: "/photos/medium/h84.jpg",
    smallPath: "/photos/small/h84.jpg",
    photoId: "h84",
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h85.jpg",
    mediumPath: "/photos/medium/h85.jpg",
    smallPath: "/photos/small/h85.jpg",
    photoId: "h85",
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h86.jpg",
    mediumPath: "/photos/medium/h86.jpg",
    smallPath: "/photos/small/h86.jpg",
    photoId: "h86",
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h87.jpg",
    mediumPath: "/photos/medium/h87.jpg",
    smallPath: "/photos/small/h87.jpg",
    photoId: "h87",
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h88.jpg",
    mediumPath: "/photos/medium/h88.jpg",
    smallPath: "/photos/small/h88.jpg",
    photoId: "h88",
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h89.jpg",
    mediumPath: "/photos/medium/h89.jpg",
    smallPath: "/photos/small/h89.jpg",
    photoId: "h89",
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h90.jpg",
    mediumPath: "/photos/medium/h90.jpg",
    smallPath: "/photos/small/h90.jpg",
    photoId: "h90",
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h91.jpg",
    mediumPath: "/photos/medium/h91.jpg",
    smallPath: "/photos/small/h91.jpg",
    photoId: "h91",
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h92.jpg",
    mediumPath: "/photos/medium/h92.jpg",
    smallPath: "/photos/small/h92.jpg",
    photoId: "h92",
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h93.jpg",
    mediumPath: "/photos/medium/h93.jpg",
    smallPath: "/photos/small/h93.jpg",
    photoId: "h93",
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h94.jpg",
    mediumPath: "/photos/medium/h94.jpg",
    smallPath: "/photos/small/h94.jpg",
    photoId: "h94",
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h95.jpg",
    mediumPath: "/photos/medium/h95.jpg",
    smallPath: "/photos/small/h95.jpg",
    photoId: "h95",
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h96.jpg",
    mediumPath: "/photos/medium/h96.jpg",
    smallPath: "/photos/small/h96.jpg",
    photoId: "h96",
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h97.jpg",
    mediumPath: "/photos/medium/h97.jpg",
    smallPath: "/photos/small/h97.jpg",
    photoId: "h97",
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h98.jpg",
    mediumPath: "/photos/medium/h98.jpg",
    smallPath: "/photos/small/h98.jpg",
    photoId: "h98",
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h99.jpg",
    mediumPath: "/photos/medium/h99.jpg",
    smallPath: "/photos/small/h99.jpg",
    photoId: "h99",
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h100.jpg",
    mediumPath: "/photos/medium/h100.jpg",
    smallPath: "/photos/small/h100.jpg",
    photoId: "h100",
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h101.jpg",
    mediumPath: "/photos/medium/h101.jpg",
    smallPath: "/photos/small/h101.jpg",
    photoId: "h101",
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h102.jpg",
    mediumPath: "/photos/medium/h102.jpg",
    smallPath: "/photos/small/h102.jpg",
    photoId: "h102",
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h103.jpg",
    mediumPath: "/photos/medium/h103.jpg",
    smallPath: "/photos/small/h103.jpg",
    photoId: "h103",
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h104.jpg",
    mediumPath: "/photos/medium/h104.jpg",
    smallPath: "/photos/small/h104.jpg",
    photoId: "h104",
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h105.jpg",
    mediumPath: "/photos/medium/h105.jpg",
    smallPath: "/photos/small/h105.jpg",
    photoId: "h105",
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h106.jpg",
    mediumPath: "/photos/medium/h106.jpg",
    smallPath: "/photos/small/h106.jpg",
    photoId: "h106",
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h107.jpg",
    mediumPath: "/photos/medium/h107.jpg",
    smallPath: "/photos/small/h107.jpg",
    photoId: "h107",
    isVertical: false,
  },
];

export const PHOTOS_ORDER = [
  "v0",
  "h0",
  "h1",
  "h2",
  "h3",
  "h4",
  "h5",
  "h6",
  "h7",
  "v1",
  "h8",
  "h9",
  "h10",
  "h11",
  "h12",
  "h13",
  "h14",
  "h15",
  "v2",
  "h16",
  "h17",

  "v3",
  "h18",
  "h19",
  "h20",
  "h21",
  "h22",
  "h23",
  "h24",
  "h25",
  "v4",
  "h26",
  "h27",
  "h28",
  "h29",
  "h30",
  "h31",
  "h32",
  "h33",
  "v5",
  "h34",
  "h35",

  "v6",
  "h36",
  "h37",
  "h38",
  "h39",
  "h40",
  "h41",
  "h42",
  "h43",
  "v7",
  "h44",
  "h45",
  "h46",
  "h47",
  "h48",
  "h49",
  "h50",
  "h51",
  "v8",
  "h52",
  "h53",

  "v9",
  "h54",
  "h55",
  "h56",
  "h57",
  "h58",
  "h59",
  "h60",
  "h61",
  "v10",
  "h62",
  "h63",
  "h64",
  "h65",
  "h66",
  "h67",
  "h68",
  "h69",
  "v11",
  "h70",
  "h71",

  "v12",
  "h72",
  "h73",
  "h74",
  "h75",
  "h76",
  "h77",
  "h78",
  "h79",
  "v13",
  "h80",
  "h81",
  "h82",
  "h83",
  "h84",
  "h85",
  "h86",
  "h87",
  "v14",
  "h88",
  "h89",

  "v15",
  "h90",
  "h91",
  "h92",
  "h93",
  "h94",
  "h95",
  "h96",
  "h97",
  "v16",
  "h98",
  "h99",
  "h100",
  "h101",
  "h102",
  "h103",
  "h104",
  "h105",
  "v17",
  "h106",
  "h107",
];
