import { PhotoInfo } from "@/types/photoInfo";

export const VERTICAL_PHOTOS: PhotoInfo[] = [
  {
    bigPath: "/photos/big/v/0.jpg",
    mediumPath: "/photos/medium/v/0.jpg",
    smallPath: "/photos/small/v/0.jpg",
    photoId: 0,
    isVertical: true,
  },
  {
    bigPath: "/photos/big/v/1.jpg",
    mediumPath: "/photos/medium/v/1.jpg",
    smallPath: "/photos/small/v/1.jpg",
    photoId: 7,
    isVertical: true,
  },
  {
    bigPath: "/photos/big/v/2.jpg",
    mediumPath: "/photos/medium/v/2.jpg",
    smallPath: "/photos/small/v/2.jpg",
    photoId: 14,
    isVertical: true,
  },
  {
    bigPath: "/photos/big/v/3.jpg",
    mediumPath: "/photos/medium/v/3.jpg",
    smallPath: "/photos/small/v/3.jpg",
    photoId: 21,
    isVertical: true,
  },
  {
    bigPath: "/photos/big/v/4.jpg",
    mediumPath: "/photos/medium/v/4.jpg",
    smallPath: "/photos/small/v/4.jpg",
    photoId: 28,
    isVertical: true,
  },
  {
    bigPath: "/photos/big/v/5.jpg",
    mediumPath: "/photos/medium/v/5.jpg",
    smallPath: "/photos/small/v/5.jpg",
    photoId: 35,
    isVertical: true,
  },
  {
    bigPath: "/photos/big/v/6.jpg",
    mediumPath: "/photos/medium/v/6.jpg",
    smallPath: "/photos/small/v/6.jpg",
    photoId: 42,
    isVertical: true,
  },
  {
    bigPath: "/photos/big/v/7.jpg",
    mediumPath: "/photos/medium/v/7.jpg",
    smallPath: "/photos/small/v/7.jpg",
    photoId: 49,
    isVertical: true,
  },
  {
    bigPath: "/photos/big/v/8.jpg",
    mediumPath: "/photos/medium/v/8.jpg",
    smallPath: "/photos/small/v/8.jpg",
    photoId: 56,
    isVertical: true,
  },
  {
    bigPath: "/photos/big/v/9.jpg",
    mediumPath: "/photos/medium/v/9.jpg",
    smallPath: "/photos/small/v/9.jpg",
    photoId: 63,
    isVertical: true,
  },
  {
    bigPath: "/photos/big/v/10.jpg",
    mediumPath: "/photos/medium/v/10.jpg",
    smallPath: "/photos/small/v/10.jpg",
    photoId: 70,
    isVertical: true,
  },
  {
    bigPath: "/photos/big/v/11.jpg",
    mediumPath: "/photos/medium/v/11.jpg",
    smallPath: "/photos/small/v/11.jpg",
    photoId: 77,
    isVertical: true,
  },
  {
    bigPath: "/photos/big/v/12.jpg",
    mediumPath: "/photos/medium/v/12.jpg",
    smallPath: "/photos/small/v/12.jpg",
    photoId: 84,
    isVertical: true,
  },
  {
    bigPath: "/photos/big/v/13.jpg",
    mediumPath: "/photos/medium/v/13.jpg",
    smallPath: "/photos/small/v/13.jpg",
    photoId: 91,
    isVertical: true,
  },
  {
    bigPath: "/photos/big/v/14.jpg",
    mediumPath: "/photos/medium/v/14.jpg",
    smallPath: "/photos/small/v/14.jpg",
    photoId: 98,
    isVertical: true,
  },
  {
    bigPath: "/photos/big/v/15.jpg",
    mediumPath: "/photos/medium/v/15.jpg",
    smallPath: "/photos/small/v/15.jpg",
    photoId: 105,
    isVertical: true,
  },
  {
    bigPath: "/photos/big/v/16.jpg",
    mediumPath: "/photos/medium/v/16.jpg",
    smallPath: "/photos/small/v/16.jpg",
    photoId: 112,
    isVertical: true,
  },
  {
    bigPath: "/photos/big/v/17.jpg",
    mediumPath: "/photos/medium/v/17.jpg",
    smallPath: "/photos/small/v/17.jpg",
    photoId: 119,
    isVertical: true,
  },
];

export const HORIZONTAL_PHOTOS: PhotoInfo[] = [
  {
    bigPath: "/photos/big/h/0.jpg",
    mediumPath: "/photos/medium/h/0.jpg",
    smallPath: "/photos/small/h/0.jpg",
    photoId: 1,
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h/1.jpg",
    mediumPath: "/photos/medium/h/1.jpg",
    smallPath: "/photos/small/h/1.jpg",
    photoId: 2,
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h/2.jpg",
    mediumPath: "/photos/medium/h/2.jpg",
    smallPath: "/photos/small/h/2.jpg",
    photoId: 3,
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h/3.jpg",
    mediumPath: "/photos/medium/h/3.jpg",
    smallPath: "/photos/small/h/3.jpg",
    photoId: 4,
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h/4.jpg",
    mediumPath: "/photos/medium/h/4.jpg",
    smallPath: "/photos/small/h/4.jpg",
    photoId: 5,
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h/5.jpg",
    mediumPath: "/photos/medium/h/5.jpg",
    smallPath: "/photos/small/h/5.jpg",
    photoId: 6,
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h/6.jpg",
    mediumPath: "/photos/medium/h/6.jpg",
    smallPath: "/photos/small/h/6.jpg",
    photoId: 8,
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h/7.jpg",
    mediumPath: "/photos/medium/h/7.jpg",
    smallPath: "/photos/small/h/7.jpg",
    photoId: 9,
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h/8.jpg",
    mediumPath: "/photos/medium/h/8.jpg",
    smallPath: "/photos/small/h/8.jpg",
    photoId: 10,
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h/9.jpg",
    mediumPath: "/photos/medium/h/9.jpg",
    smallPath: "/photos/small/h/9.jpg",
    photoId: 11,
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h/10.jpg",
    mediumPath: "/photos/medium/h/10.jpg",
    smallPath: "/photos/small/h/10.jpg",
    photoId: 12,
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h/11.jpg",
    mediumPath: "/photos/medium/h/11.jpg",
    smallPath: "/photos/small/h/11.jpg",
    photoId: 13,
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h/12.jpg",
    mediumPath: "/photos/medium/h/12.jpg",
    smallPath: "/photos/small/h/12.jpg",
    photoId: 15,
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h/13.jpg",
    mediumPath: "/photos/medium/h/13.jpg",
    smallPath: "/photos/small/h/13.jpg",
    photoId: 16,
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h/14.jpg",
    mediumPath: "/photos/medium/h/14.jpg",
    smallPath: "/photos/small/h/14.jpg",
    photoId: 17,
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h/15.jpg",
    mediumPath: "/photos/medium/h/15.jpg",
    smallPath: "/photos/small/h/15.jpg",
    photoId: 18,
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h/16.jpg",
    mediumPath: "/photos/medium/h/16.jpg",
    smallPath: "/photos/small/h/16.jpg",
    photoId: 19,
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h/17.jpg",
    mediumPath: "/photos/medium/h/17.jpg",
    smallPath: "/photos/small/h/17.jpg",
    photoId: 20,
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h/18.jpg",
    mediumPath: "/photos/medium/h/18.jpg",
    smallPath: "/photos/small/h/18.jpg",
    photoId: 22,
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h/19.jpg",
    mediumPath: "/photos/medium/h/19.jpg",
    smallPath: "/photos/small/h/19.jpg",
    photoId: 23,
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h/20.jpg",
    mediumPath: "/photos/medium/h/20.jpg",
    smallPath: "/photos/small/h/20.jpg",
    photoId: 24,
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h/21.jpg",
    mediumPath: "/photos/medium/h/21.jpg",
    smallPath: "/photos/small/h/21.jpg",
    photoId: 25,
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h/22.jpg",
    mediumPath: "/photos/medium/h/22.jpg",
    smallPath: "/photos/small/h/22.jpg",
    photoId: 26,
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h/23.jpg",
    mediumPath: "/photos/medium/h/23.jpg",
    smallPath: "/photos/small/h/23.jpg",
    photoId: 27,
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h/24.jpg",
    mediumPath: "/photos/medium/h/24.jpg",
    smallPath: "/photos/small/h/24.jpg",
    photoId: 29,
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h/25.jpg",
    mediumPath: "/photos/medium/h/25.jpg",
    smallPath: "/photos/small/h/25.jpg",
    photoId: 30,
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h/26.jpg",
    mediumPath: "/photos/medium/h/26.jpg",
    smallPath: "/photos/small/h/26.jpg",
    photoId: 31,
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h/27.jpg",
    mediumPath: "/photos/medium/h/27.jpg",
    smallPath: "/photos/small/h/27.jpg",
    photoId: 32,
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h/28.jpg",
    mediumPath: "/photos/medium/h/28.jpg",
    smallPath: "/photos/small/h/28.jpg",
    photoId: 33,
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h/29.jpg",
    mediumPath: "/photos/medium/h/29.jpg",
    smallPath: "/photos/small/h/29.jpg",
    photoId: 34,
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h/30.jpg",
    mediumPath: "/photos/medium/h/30.jpg",
    smallPath: "/photos/small/h/30.jpg",
    photoId: 36,
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h/31.jpg",
    mediumPath: "/photos/medium/h/31.jpg",
    smallPath: "/photos/small/h/31.jpg",
    photoId: 37,
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h/32.jpg",
    mediumPath: "/photos/medium/h/32.jpg",
    smallPath: "/photos/small/h/32.jpg",
    photoId: 38,
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h/33.jpg",
    mediumPath: "/photos/medium/h/33.jpg",
    smallPath: "/photos/small/h/33.jpg",
    photoId: 39,
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h/34.jpg",
    mediumPath: "/photos/medium/h/34.jpg",
    smallPath: "/photos/small/h/34.jpg",
    photoId: 40,
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h/35.jpg",
    mediumPath: "/photos/medium/h/35.jpg",
    smallPath: "/photos/small/h/35.jpg",
    photoId: 41,
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h/36.jpg",
    mediumPath: "/photos/medium/h/36.jpg",
    smallPath: "/photos/small/h/36.jpg",
    photoId: 43,
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h/37.jpg",
    mediumPath: "/photos/medium/h/37.jpg",
    smallPath: "/photos/small/h/37.jpg",
    photoId: 44,
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h/38.jpg",
    mediumPath: "/photos/medium/h/38.jpg",
    smallPath: "/photos/small/h/38.jpg",
    photoId: 45,
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h/39.jpg",
    mediumPath: "/photos/medium/h/39.jpg",
    smallPath: "/photos/small/h/39.jpg",
    photoId: 46,
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h/40.jpg",
    mediumPath: "/photos/medium/h/40.jpg",
    smallPath: "/photos/small/h/40.jpg",
    photoId: 47,
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h/41.jpg",
    mediumPath: "/photos/medium/h/41.jpg",
    smallPath: "/photos/small/h/41.jpg",
    photoId: 48,
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h/42.jpg",
    mediumPath: "/photos/medium/h/42.jpg",
    smallPath: "/photos/small/h/42.jpg",
    photoId: 50,
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h/43.jpg",
    mediumPath: "/photos/medium/h/43.jpg",
    smallPath: "/photos/small/h/43.jpg",
    photoId: 51,
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h/44.jpg",
    mediumPath: "/photos/medium/h/44.jpg",
    smallPath: "/photos/small/h/44.jpg",
    photoId: 52,
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h/45.jpg",
    mediumPath: "/photos/medium/h/45.jpg",
    smallPath: "/photos/small/h/45.jpg",
    photoId: 53,
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h/46.jpg",
    mediumPath: "/photos/medium/h/46.jpg",
    smallPath: "/photos/small/h/46.jpg",
    photoId: 54,
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h/47.jpg",
    mediumPath: "/photos/medium/h/47.jpg",
    smallPath: "/photos/small/h/47.jpg",
    photoId: 55,
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h/48.jpg",
    mediumPath: "/photos/medium/h/48.jpg",
    smallPath: "/photos/small/h/48.jpg",
    photoId: 57,
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h/49.jpg",
    mediumPath: "/photos/medium/h/49.jpg",
    smallPath: "/photos/small/h/49.jpg",
    photoId: 58,
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h/50.jpg",
    mediumPath: "/photos/medium/h/50.jpg",
    smallPath: "/photos/small/h/50.jpg",
    photoId: 59,
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h/51.jpg",
    mediumPath: "/photos/medium/h/51.jpg",
    smallPath: "/photos/small/h/51.jpg",
    photoId: 60,
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h/52.jpg",
    mediumPath: "/photos/medium/h/52.jpg",
    smallPath: "/photos/small/h/52.jpg",
    photoId: 61,
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h/53.jpg",
    mediumPath: "/photos/medium/h/53.jpg",
    smallPath: "/photos/small/h/53.jpg",
    photoId: 62,
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h/54.jpg",
    mediumPath: "/photos/medium/h/54.jpg",
    smallPath: "/photos/small/h/54.jpg",
    photoId: 64,
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h/55.jpg",
    mediumPath: "/photos/medium/h/55.jpg",
    smallPath: "/photos/small/h/55.jpg",
    photoId: 65,
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h/56.jpg",
    mediumPath: "/photos/medium/h/56.jpg",
    smallPath: "/photos/small/h/56.jpg",
    photoId: 66,
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h/57.jpg",
    mediumPath: "/photos/medium/h/57.jpg",
    smallPath: "/photos/small/h/57.jpg",
    photoId: 67,
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h/58.jpg",
    mediumPath: "/photos/medium/h/58.jpg",
    smallPath: "/photos/small/h/58.jpg",
    photoId: 68,
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h/59.jpg",
    mediumPath: "/photos/medium/h/59.jpg",
    smallPath: "/photos/small/h/59.jpg",
    photoId: 69,
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h/60.jpg",
    mediumPath: "/photos/medium/h/60.jpg",
    smallPath: "/photos/small/h/60.jpg",
    photoId: 71,
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h/61.jpg",
    mediumPath: "/photos/medium/h/61.jpg",
    smallPath: "/photos/small/h/61.jpg",
    photoId: 72,
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h/62.jpg",
    mediumPath: "/photos/medium/h/62.jpg",
    smallPath: "/photos/small/h/62.jpg",
    photoId: 73,
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h/63.jpg",
    mediumPath: "/photos/medium/h/63.jpg",
    smallPath: "/photos/small/h/63.jpg",
    photoId: 74,
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h/64.jpg",
    mediumPath: "/photos/medium/h/64.jpg",
    smallPath: "/photos/small/h/64.jpg",
    photoId: 75,
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h/65.jpg",
    mediumPath: "/photos/medium/h/65.jpg",
    smallPath: "/photos/small/h/65.jpg",
    photoId: 76,
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h/66.jpg",
    mediumPath: "/photos/medium/h/66.jpg",
    smallPath: "/photos/small/h/66.jpg",
    photoId: 78,
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h/67.jpg",
    mediumPath: "/photos/medium/h/67.jpg",
    smallPath: "/photos/small/h/67.jpg",
    photoId: 79,
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h/68.jpg",
    mediumPath: "/photos/medium/h/68.jpg",
    smallPath: "/photos/small/h/68.jpg",
    photoId: 80,
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h/69.jpg",
    mediumPath: "/photos/medium/h/69.jpg",
    smallPath: "/photos/small/h/69.jpg",
    photoId: 81,
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h/70.jpg",
    mediumPath: "/photos/medium/h/70.jpg",
    smallPath: "/photos/small/h/70.jpg",
    photoId: 82,
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h/71.jpg",
    mediumPath: "/photos/medium/h/71.jpg",
    smallPath: "/photos/small/h/71.jpg",
    photoId: 83,
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h/72.jpg",
    mediumPath: "/photos/medium/h/72.jpg",
    smallPath: "/photos/small/h/72.jpg",
    photoId: 85,
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h/73.jpg",
    mediumPath: "/photos/medium/h/73.jpg",
    smallPath: "/photos/small/h/73.jpg",
    photoId: 86,
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h/74.jpg",
    mediumPath: "/photos/medium/h/74.jpg",
    smallPath: "/photos/small/h/74.jpg",
    photoId: 87,
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h/75.jpg",
    mediumPath: "/photos/medium/h/75.jpg",
    smallPath: "/photos/small/h/75.jpg",
    photoId: 88,
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h/76.jpg",
    mediumPath: "/photos/medium/h/76.jpg",
    smallPath: "/photos/small/h/76.jpg",
    photoId: 89,
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h/77.jpg",
    mediumPath: "/photos/medium/h/77.jpg",
    smallPath: "/photos/small/h/77.jpg",
    photoId: 90,
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h/78.jpg",
    mediumPath: "/photos/medium/h/78.jpg",
    smallPath: "/photos/small/h/78.jpg",
    photoId: 92,
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h/79.jpg",
    mediumPath: "/photos/medium/h/79.jpg",
    smallPath: "/photos/small/h/79.jpg",
    photoId: 93,
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h/80.jpg",
    mediumPath: "/photos/medium/h/80.jpg",
    smallPath: "/photos/small/h/80.jpg",
    photoId: 94,
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h/81.jpg",
    mediumPath: "/photos/medium/h/81.jpg",
    smallPath: "/photos/small/h/81.jpg",
    photoId: 95,
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h/82.jpg",
    mediumPath: "/photos/medium/h/82.jpg",
    smallPath: "/photos/small/h/82.jpg",
    photoId: 96,
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h/83.jpg",
    mediumPath: "/photos/medium/h/83.jpg",
    smallPath: "/photos/small/h/83.jpg",
    photoId: 97,
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h/84.jpg",
    mediumPath: "/photos/medium/h/84.jpg",
    smallPath: "/photos/small/h/84.jpg",
    photoId: 99,
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h/85.jpg",
    mediumPath: "/photos/medium/h/85.jpg",
    smallPath: "/photos/small/h/85.jpg",
    photoId: 100,
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h/86.jpg",
    mediumPath: "/photos/medium/h/86.jpg",
    smallPath: "/photos/small/h/86.jpg",
    photoId: 101,
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h/87.jpg",
    mediumPath: "/photos/medium/h/87.jpg",
    smallPath: "/photos/small/h/87.jpg",
    photoId: 102,
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h/88.jpg",
    mediumPath: "/photos/medium/h/88.jpg",
    smallPath: "/photos/small/h/88.jpg",
    photoId: 103,
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h/89.jpg",
    mediumPath: "/photos/medium/h/89.jpg",
    smallPath: "/photos/small/h/89.jpg",
    photoId: 104,
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h/90.jpg",
    mediumPath: "/photos/medium/h/90.jpg",
    smallPath: "/photos/small/h/90.jpg",
    photoId: 106,
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h/91.jpg",
    mediumPath: "/photos/medium/h/91.jpg",
    smallPath: "/photos/small/h/91.jpg",
    photoId: 107,
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h/92.jpg",
    mediumPath: "/photos/medium/h/92.jpg",
    smallPath: "/photos/small/h/92.jpg",
    photoId: 108,
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h/93.jpg",
    mediumPath: "/photos/medium/h/93.jpg",
    smallPath: "/photos/small/h/93.jpg",
    photoId: 109,
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h/94.jpg",
    mediumPath: "/photos/medium/h/94.jpg",
    smallPath: "/photos/small/h/94.jpg",
    photoId: 110,
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h/95.jpg",
    mediumPath: "/photos/medium/h/95.jpg",
    smallPath: "/photos/small/h/95.jpg",
    photoId: 111,
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h/96.jpg",
    mediumPath: "/photos/medium/h/96.jpg",
    smallPath: "/photos/small/h/96.jpg",
    photoId: 113,
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h/97.jpg",
    mediumPath: "/photos/medium/h/97.jpg",
    smallPath: "/photos/small/h/97.jpg",
    photoId: 114,
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h/98.jpg",
    mediumPath: "/photos/medium/h/98.jpg",
    smallPath: "/photos/small/h/98.jpg",
    photoId: 115,
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h/99.jpg",
    mediumPath: "/photos/medium/h/99.jpg",
    smallPath: "/photos/small/h/99.jpg",
    photoId: 116,
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h/100.jpg",
    mediumPath: "/photos/medium/h/100.jpg",
    smallPath: "/photos/small/h/100.jpg",
    photoId: 117,
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h/101.jpg",
    mediumPath: "/photos/medium/h/101.jpg",
    smallPath: "/photos/small/h/101.jpg",
    photoId: 118,
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h/102.jpg",
    mediumPath: "/photos/medium/h/102.jpg",
    smallPath: "/photos/small/h/102.jpg",
    photoId: 120,
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h/103.jpg",
    mediumPath: "/photos/medium/h/103.jpg",
    smallPath: "/photos/small/h/103.jpg",
    photoId: 121,
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h/104.jpg",
    mediumPath: "/photos/medium/h/104.jpg",
    smallPath: "/photos/small/h/104.jpg",
    photoId: 122,
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h/105.jpg",
    mediumPath: "/photos/medium/h/105.jpg",
    smallPath: "/photos/small/h/105.jpg",
    photoId: 123,
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h/106.jpg",
    mediumPath: "/photos/medium/h/106.jpg",
    smallPath: "/photos/small/h/106.jpg",
    photoId: 124,
    isVertical: false,
  },
  {
    bigPath: "/photos/big/h/107.jpg",
    mediumPath: "/photos/medium/h/107.jpg",
    smallPath: "/photos/small/h/107.jpg",
    photoId: 125,
    isVertical: false,
  },
];
